GET http://localhost:3003/api/notes/
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2NhMDYwYjkwMzBkZmJlMDI3MzhlMiIsImZpcnN0TmFtZSI6InJvb3QyIiwiZW1haWwiOiJyb290QGV4YW1wbGUuY29tIiwiaWF0IjoxNzAyODUwNDE1fQ.e7zuhxylqcQEXXeVsaQeSbz_iwCHRVdQYchhnoF4Ozw

{}