POST http://localhost:3003/api/notes/create
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTkzYjExZWU1ZDRjYmFkZmJjNTViYSIsIm5hbWV1c2VyIjoibHVpc1VzZXIiLCJpYXQiOjE2OTczMzkwOTJ9.Wmz9OEpETzH7UhVwJm1d6L3ZGrP0TijCviW3DogFzpY

{
    "title": "Nota prueba v8",
    "content": "nota de prueba v8"
}